### ISSUE TITLE
Sensu Go Docker sandbox

### ISSUE THREAD

**Issue by apaskulin** [sensu/sandbox#31]
Create a sandbox in this repo using Docker and Sensu Go with pre-installed pipelines and tools, based on https://github.com/sensu/sensu-go/blob/master/docker-compose.yaml and https://github.com/calebhailey/sensu-go-demo/blob/master/docker-compose.yml

Requirements:

- Sensu Go
- InfluxDB
- Grafana
- Nginx
- Example resource definitions (https://github.com/calebhailey/sensu-go-demo/tree/master/manifests)

Structure:
- Deploy Sensu with Docker
  - Deploy a backend
- Lesson 1: Create a monitoring event
  - Use the events API to create an event. Use the /auth endpoint to get an access token, but include a warning about that the endpoint is experimental and not for production use.
  - See the event in the dashboard and using sensuctl.
- Lesson 2: Create an event pipeline
  - Set up https://bonsai.sensu.io/assets/sensu/sensu-slack-handler.
  - Use the events API to send an event to Slack.
- Lesson 3: Automate event production with the Sensu agent
  - Deploy an agent
  - Set up an influxdb asset and handler
  - Set up a sensu-plugins-http asset with a ruby runtime asset
  - Set up a check

**Comment by apaskulin** [comment]
Closing in favor of https://docs.sensu.io/sensu-go/5.2/getting-started/sample-app/

**Comment by apaskulin** [comment]
To do:

- [ ] Use official images

**Comment by jspaleta** [comment]
This command will create a container named `sensu-agent`  and will connect to the docker network
`sensu-go-docker_default`   The sensu-agent will connect to the backend server as entity named `sandbox-agent`

```
docker run -d --name sensu-agent --network sensu-go-docker_default sensu/sensu:latest sensu-agent start --backend-url ws://sensu-backend:8081 --subscriptions "sandbox" --name "sandbox-agent" 
```

The name of the network maybe different for you docker-compose is choosing the network name because we aren't be explicit about it yet in the compose file.  You should see a message about network being setup when you run the compose up.  You can check the networks docker is management with `docker network ls`

**Comment by apaskulin** [comment]
Closed by https://github.com/sensu/sandbox/tree/master/sensu-go-docker
